import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";
import { PractiseModal } from "@/components/modals/practise-modal";
import Head from "next/head";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LingoQuest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <link rel="icon" href="/favicon.ico" />
          {/* Add more meta tags or links here if needed */}
        </Head>
        <body className={font.className}>
          <Toaster />
          <HeartsModal />
          <ExitModal />
          <PractiseModal />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
